### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by virak0001** [pnc-virtual-company/2020-G2-letsgo#9]

**Comment by sreyrot** [comment]
@sengseiha-sam, please teacher help to review my task already completed.

**Comment by Sethmok** [comment]
Hi @virak0001 , to answer your question on email, yes I think it's a good idea to include a filed for user to fill in their first and last name. I also want to include 2 more fields for their "Sex" and "Date of Birth". Also okay to include a field to verify password.
